### ISSUE TITLE
Add boot.scr and boot.cmd creation to ev3 builds for deployment

### ISSUE THREAD

**Issue by oaken-source** [ninjastorms/ninjastorms#10]

**Comment by pepijndevos** [comment]
I'm trying to figure out how to do this. It seems almost as simple as copying the following section to `Makefile.am`

```
boot.scr: boot.cmd
	@echo "  MKIMAGE  boot.scr"
	$(Q)mkimage -C none -A arm -T script -d boot.cmd boot.scr

boot.cmd: disas
	$(Q)echo "loady $(LOADADDR)" > boot.cmd
	$(Q)echo "go 0x$(shell grep '<$(ENTRY)>' $(ASM) | head -n1 | cut -d' ' -f1)" >> boot.cmd
```

Except we want to get rid of the `disas` and `grep` stuff, but to do so I need to get a better understanding of the ld script and u-boot. Bascially there are a few too many places that have a notion of a base address or entry point.

In [Raspberry Pi Bare Bones](http://wiki.osdev.org/Raspberry_Pi_Bare_Bones#Linking_the_Kernel) we see that they use `. = 0x8000;` to define the base address of the `.text.boot` block, while in [Beaglebone](http://wiki.osdev.org/ARM_Beagleboard#Linker_Script) they use

```
MEMORY
{
    ram : ORIGIN = 0x80200000, LENGTH = 0x10000
}
```
Where `0x80200000` is the address passed to `loady` (the default) and use the same address for the subsequent `go` command.

In our linker script we use neither, yet disassembly with the current build system shows that indeed the address of `Start` is equal to `LOADADDR`, so I think the following should suffice

```
boot.scr: boot.cmd
	@echo "  MKIMAGE  boot.scr"
	$(Q)mkimage -C none -A arm -T script -d boot.cmd boot.scr

boot.cmd:
	$(Q)echo "loady $(LOADADDR)" > boot.cmd
	$(Q)echo "go $(LOADADDR)" >> boot.cmd
```

**Comment by oaken-source** [comment]
yes, uImage would probably be the way forward if we can make it happen. I think the boot.scr that we used was a relic of some bare-metal deployment tutorial that we followed in the early stages of the project.

However, I was under the impression that uImage is a linux specific concept, but if we can make it work in our context that would be sweet.

**Comment by oaken-source** [comment]
Also, the load adresses and entry points vary between different boards, so they are set at configure time in the configure.ac script.

**Comment by pepijndevos** [comment]
The `-O linux` sets the OS type, which as far as I understand, means that your program gets an initrd and flat device tree passed as arguments. I did not explore other setting in detail.

It's worth noting that some people on the OSdev forums seem to implement executable loading from initrd before full file system support is implemented.

I did see that qemu has a different base address, but due to our link script and [this line](https://github.com/ninjastorms/ninjastorms/blob/master/Makefile.am#L50), `Start` will always be at that address, no? So I think the above should work. (I'll test next week when I'm back home with the EV3)

**Comment by pepijndevos** [comment]
The current master doesn't run for me yet, but I can confirm the uImage approach works.
The image was generated using
```
mkimage -C none -A arm -T kernel -O linux -a 0xC1000000 -e 0xC10008A4 -d ev3ninja.bin uImage
```
Which I copied to a FAT volume on a SD card. Upon boot I saw the following output:

```
EV3 initialization passed!
Booting EV3 EEprom Boot Loader

	EEprom Version:   0.60
	EV3 Flashtype:    N25Q128A13B

EV3 Booting system 

Jumping to entry point at: 0xC1080000


U-Boot 2009.11 (Oct 26 2012 - 10:30:38)

I2C:   ready
DRAM:  64 MB
MMC:   davinci: 0
In:    serial
Out:   serial
Err:   serial
ARM Clock : 300000000 Hz
DDR Clock : 132000000 Hz
Invalid MAC address read.
Hit 'l' to stop autoboot:  0 
reading boot.scr

** Unable to read "boot.scr" from mmc 0:1 **
reading uImage

73404 bytes read
## Booting kernel from Legacy Image at c0007fc0 ...
   Image Name:   
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    73340 Bytes = 71.6 kB
   Load Address: c1000000
   Entry Point:  c10008a4
   Loading Kernel Image ... OK
OK

Starting kernel ...

This is EV3 NinjaStorms
  shuriken ready
```
