### ISSUE TITLE
Unable to get project working

### ISSUE THREAD

**Issue by oscartbeaumont** [ninjastorms/ninjastorms#14]
Hello,
This project really interests me for a way of learning about operating systems and I have been unable to get it running. I am doing the build on a Mac and I have been using the procedure documented below.
```bash
git clone https://github.com/ninjastorms/ninjastorms.git
cd ninjastorms
./autogen.sh
./configure
make
```
When running `make` I get the error:
```bash
/Library/Developer/CommandLineTools/usr/bin/make  all-am
make[1]: Nothing to be done for `all-am'
```
I am trying to get the OS to build for my EV3. I tried to just use `arm-none-eabi-gcc` and `mkimage` directly from the command line to build the OS but continually run into errors with invalid instructions in the assembly code but this was likely due to missing or incorrect flags as I am not extremely familiar with OS development and the build tooling (`make`, `gcc`, `mkimage`, etc).
Any help for getting this working would be greatly appreciated.

**Comment by oaken-source** [comment]
Hi, sorry for leaving this open for so long. Take a look at the README, it outlines how the project needs to be configured and compiled and booted. Your configure call is incomplete.
