### ISSUE TITLE
Use a linker script

### ISSUE THREAD

**Issue by pepijndevos** [ninjastorms/ninjastorms#6]
The current deployment target disassembles the binary to locate the entry point. A better solution would be to use a linker script to link specific parts to known locations.

Example: [OSdev / Raspbery Pi Bare Bones / linking the kernel](http://wiki.osdev.org/Raspberry_Pi_Bare_Bones#Linking_the_Kernel)

**Comment by oaken-source** [comment]
I just noticed that the autotools build actually uses a linker script already: kernel/link-arm-eabi.ld

**Comment by oaken-source** [comment]
putting this on hold until #9 is resolved.

**Comment by pepijndevos** [comment]
Link script is working.
