### ISSUE TITLE
Link with libgcc

### ISSUE THREAD

**Issue by pepijndevos** [ninjastorms/ninjastorms#7]
Currently, a custom toolchain and homegrown implementations of some libc functions are used to avoid link errors due to gcc using some internal functions. To avoid this, the kernel should be linked with libgcc. This is discussed in [OSdev / libgcc](http://wiki.osdev.org/Libgcc)

**Comment by oaken-source** [comment]
The custom toolchain is not really custom - any arm-none-eabi (bare metal arm) toolchain will do the job - so I don't think this relates to this particular issue. the homegrown implementations of the libc functions don't seem to interfere with this issue either, as libc and libgcc are entirely separate things.

I am actually not sure what currently avoids the problem of gcc emitting calls to functions in libgcc. They *should* be emitted. I don't know why they are not. But we should definitely start linking against libgcc. I'm getting my build environment back in shape, and then I'll be adding that.

**Comment by oaken-source** [comment]
fixed in e8821fbea0c53741d2a9c7a989590de1b891ba3e
