### ISSUE TITLE
Move automake build system to a different branch

### ISSUE THREAD

**Issue by pepijndevos** [ninjastorms/ninjastorms#9]
Current master lacks features compared to the old Makefile, most notably the deploy target, which is not documented elsewhere. It is IMHO also more complex and opaque, but that might just be my inexperience with automake (as a dev rather than a library consumer).

I would suggest making a new branch from 089f98d3f62854d75b144cf62e595e8cfe01cd42 (last commit before automake changes) and cherry-picking remaining changes not related to automake, and make that the default branch. (I don't think there is a way I can do this as a PR)

**Comment by oaken-source** [comment]
I think I am in favour of keeping the autoconf / automake solution. A standard build system is almost always preferable to handcrafted Makefiles, although I have to admit that the configure scripts can be hard to read at times...

That being said, if readability of the configure.ac and Makefile.am files is an issue - maybe we could add some comments for documentation?

**Comment by pepijndevos** [comment]
If a suitable solution can be found to somehow automate or at least document deployment on the EV3, as was my initial question on #5, using automake is not a problem in itself.

If automake provides value, we just need to find the best way to handle the u-boot process for the EV3. If handling this in automake is not desired, maybe it could just be a standalone script or documentation.

I'll try to get it running next week once I'm reunited with my EV3.

**Comment by pepijndevos** [comment]
Automake script seems to be working fine now.
